/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../../core";

export const Coupons: core.serialization.Schema<serializers.Coupons.Raw, CorrilyApi.Coupons> =
    core.serialization.record(
        core.serialization.lazy(async () => (await import("../../..")).ProductId),
        core.serialization.string()
    );

export declare namespace Coupons {
    type Raw = Record<serializers.ProductId.Raw, string>;
}
