/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../../core";

export const Gateway: core.serialization.ObjectSchema<serializers.Gateway.Raw, CorrilyApi.Gateway> =
    core.serialization.object({
        currency: core.serialization.lazy(async () => (await import("../../..")).Currency).optional(),
        amount: core.serialization.number().optional(),
        formatted: core.serialization.string().optional(),
    });

export declare namespace Gateway {
    interface Raw {
        currency?: serializers.Currency.Raw | null;
        amount?: number | null;
        formatted?: string | null;
    }
}
