/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../../core";

export const PriceDisplay: core.serialization.ObjectSchema<serializers.PriceDisplay.Raw, CorrilyApi.PriceDisplay> =
    core.serialization.object({
        price: core.serialization.string().optional(),
        referenceIntervalPrice: core.serialization.property(
            "reference_interval_price",
            core.serialization.string().optional()
        ),
        priceWithBaselineStrike: core.serialization.property(
            "price_with_baseline_strike",
            core.serialization.string().optional()
        ),
        discountToBaseline: core.serialization.property("discount_to_baseline", core.serialization.number().optional()),
    });

export declare namespace PriceDisplay {
    interface Raw {
        price?: string | null;
        reference_interval_price?: string | null;
        price_with_baseline_strike?: string | null;
        discount_to_baseline?: number | null;
    }
}
