/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../../core";

export const PriceFeatures: core.serialization.Schema<serializers.PriceFeatures.Raw, CorrilyApi.PriceFeatures> =
    core.serialization.record(core.serialization.string(), core.serialization.string());

export declare namespace PriceFeatures {
    type Raw = Record<string, string>;
}
