/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../../core";

export const Product: core.serialization.ObjectSchema<serializers.Product.Raw, CorrilyApi.Product> =
    core.serialization.object({
        price: core.serialization.number().optional(),
        priceUsd: core.serialization.property("price_usd", core.serialization.number().optional()),
        interval: core.serialization.lazy(async () => (await import("../../..")).Interval).optional(),
        intervalCount: core.serialization.property("interval_count", core.serialization.number().optional()),
        display: core.serialization.lazyObject(async () => (await import("../../..")).PriceDisplay).optional(),
        integrations: core.serialization
            .record(
                core.serialization.lazy(async () => (await import("../../..")).Integration),
                core.serialization.lazyObject(async () => (await import("../../..")).Gateway).optional()
            )
            .optional(),
        coupon: core.serialization.unknown().optional(),
    });

export declare namespace Product {
    interface Raw {
        price?: number | null;
        price_usd?: number | null;
        interval?: serializers.Interval.Raw | null;
        interval_count?: number | null;
        display?: serializers.PriceDisplay.Raw | null;
        integrations?: Record<serializers.Integration.Raw, serializers.Gateway.Raw | null | undefined> | null;
        coupon?: unknown | null;
    }
}
