/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SubscriptionStatus = "pending" | "trialing" | "active" | "canceled";

export const SubscriptionStatus = {
  Pending: "pending",
  Trialing: "trialing",
  Active: "active",
  Canceled: "canceled",
} as const;
