/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../core";

export const GetSubscriptionResponse: core.schemas.Schema<
  serializers.GetSubscriptionResponse.Raw,
  CorrilyApi.GetSubscriptionResponse
> = core.schemas.unknown();

export declare namespace GetSubscriptionResponse {
  type Raw = unknown;
}
