/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../core";

export const UpdateSubscriptionResponse: core.schemas.Schema<
  serializers.UpdateSubscriptionResponse.Raw,
  CorrilyApi.UpdateSubscriptionResponse
> = core.schemas.unknown();

export declare namespace UpdateSubscriptionResponse {
  type Raw = unknown;
}
