/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CorrilyApi } from "@fern-api/corrily";

export interface CreateProductRequest {
  apiId: CorrilyApi.ApiId;
  name: string;
  basePx: number;
  interval: CorrilyApi.Interval;
  intervalCount: number;
  countryPrices?: CorrilyApi.CountryPrice[];
  integrations?: CorrilyApi.ProductIntegration[];
}
