/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../environments";
import * as core from "../../../core";
import { CorrilyApi } from "@fern-api/corrily";
import urlJoin from "url-join";
import * as serializers from "../../../serialization";

export declare namespace Client {
  interface Options {
    environment?: environments.CorrilyApiEnvironment | string;
    token?: core.Supplier<core.BearerToken>;
  }
}

export class Client {
  constructor(private readonly options: Client.Options) {}

  public async identify(request: CorrilyApi.IdentifyCallRequest): Promise<CorrilyApi.user.identify.Response> {
    const _response = await core.fetcher({
      url: urlJoin(this.options.environment ?? environments.CorrilyApiEnvironment.Production, "/identify/"),
      method: "POST",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
      },
      body: await serializers.user.identify.Request.json({
        userId: request.userId,
        ip: request.ip,
        features: request.features,
        appleOriginalTransactionId: request.appleOriginalTransactionId,
        googlePurchaseToken: request.googlePurchaseToken,
      }),
    });
    if (_response.ok) {
      return {
        ok: true,
        body: await serializers.user.identify.Response.parse(_response.body as serializers.user.identify.Response.Raw),
      };
    }

    return {
      ok: false,
      error: CorrilyApi.user.identify.Error._unknown(_response.error),
    };
  }
}
