/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Country = "US" | "CA" | "SG" | "IT";

export const Country = {
  Us: "US",
  Ca: "CA",
  Sg: "SG",
  It: "IT",
} as const;
