/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Currency = "USD" | "SGD" | "EUR";

export const Currency = {
  Usd: "USD",
  Sgd: "SGD",
  Eur: "EUR",
} as const;
