/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CorrilyApi } from "@fern-api/corrily";

export interface IdentifyCallRequest {
  userId: CorrilyApi.UserId;
  ip?: string;
  features?: unknown;
  appleOriginalTransactionId?: string;
  googlePurchaseToken?: string;
}
