/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class CorrilyApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, CorrilyApiTimeoutError.prototype);
    }
}
