/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../core";

export const ChargebeeIntegration: core.schemas.ObjectSchema<
  serializers.ChargebeeIntegration.Raw,
  CorrilyApi.ChargebeeIntegration
> = core.schemas.object({
  chargebeePlanId: core.schemas.property("chargebee_plan_id", core.schemas.string()),
});

export declare namespace ChargebeeIntegration {
  interface Raw {
    chargebee_plan_id: string;
  }
}
