/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../core";

export const RecurlyIntegration: core.schemas.ObjectSchema<
  serializers.RecurlyIntegration.Raw,
  CorrilyApi.RecurlyIntegration
> = core.schemas.object({
  recurlyPlanId: core.schemas.property("recurly_plan_id", core.schemas.string()),
});

export declare namespace RecurlyIntegration {
  interface Raw {
    recurly_plan_id: string;
  }
}
