/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../core";

export const StripeWithIntervalIntegration: core.schemas.ObjectSchema<
  serializers.StripeWithIntervalIntegration.Raw,
  CorrilyApi.StripeWithIntervalIntegration
> = core.schemas.object({
  stripeProductId: core.schemas.property("stripe_product_id", core.schemas.string()),
  interval: core.schemas.lazy(async () => (await import("../..")).StripeInterval),
  intervalCount: core.schemas.property("interval_count", core.schemas.number()),
});

export declare namespace StripeWithIntervalIntegration {
  interface Raw {
    stripe_product_id: string;
    interval: serializers.StripeInterval.Raw;
    interval_count: number;
  }
}
