/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../core";

export const StripeIntegration: core.schemas.ObjectSchema<
  serializers.StripeIntegration.Raw,
  CorrilyApi.StripeIntegration
> = core.schemas.object({
  stripeProductId: core.schemas.property("stripe_product_id", core.schemas.string()),
});

export declare namespace StripeIntegration {
  interface Raw {
    stripe_product_id: string;
  }
}
