/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CorrilyApi } from "@fern-api/corrily";

export interface CreateSubscriptionRequest {
    amount: number;
    country?: CorrilyApi.Country;
    created: number;
    currency: CorrilyApi.Currency;
    origin: CorrilyApi.Integration;
    originId: string;
    product: string;
    status: CorrilyApi.SubscriptionStatus;
    userId: CorrilyApi.UserId;
    cancelAt?: number;
    canceledAt?: number;
    trialEnd?: number;
    trialStart?: number;
}
