/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../../core";

export const ChargebeeIntegration: core.serialization.ObjectSchema<
    serializers.ChargebeeIntegration.Raw,
    CorrilyApi.ChargebeeIntegration
> = core.serialization.object({
    chargebeePlanId: core.serialization.property("chargebee_plan_id", core.serialization.string()),
});

export declare namespace ChargebeeIntegration {
    interface Raw {
        chargebee_plan_id: string;
    }
}
