/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../../core";

export const RecurlyIntegration: core.serialization.ObjectSchema<
    serializers.RecurlyIntegration.Raw,
    CorrilyApi.RecurlyIntegration
> = core.serialization.object({
    recurlyPlanId: core.serialization.property("recurly_plan_id", core.serialization.string()),
});

export declare namespace RecurlyIntegration {
    interface Raw {
        recurly_plan_id: string;
    }
}
