/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../../core";

export const StripeIntegration: core.serialization.ObjectSchema<
    serializers.StripeIntegration.Raw,
    CorrilyApi.StripeIntegration
> = core.serialization.object({
    stripeProductId: core.serialization.property("stripe_product_id", core.serialization.string()),
});

export declare namespace StripeIntegration {
    interface Raw {
        stripe_product_id: string;
    }
}
