/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../../core";

export const StripeWithIntervalIntegration: core.serialization.ObjectSchema<
    serializers.StripeWithIntervalIntegration.Raw,
    CorrilyApi.StripeWithIntervalIntegration
> = core.serialization.object({
    stripeProductId: core.serialization.property("stripe_product_id", core.serialization.string()),
    interval: core.serialization.lazy(async () => (await import("../../..")).StripeInterval),
    intervalCount: core.serialization.property("interval_count", core.serialization.number()),
});

export declare namespace StripeWithIntervalIntegration {
    interface Raw {
        stripe_product_id: string;
        interval: serializers.StripeInterval.Raw;
        interval_count: number;
    }
}
