/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../core";

export const CouponId: core.schemas.Schema<serializers.CouponId.Raw, CorrilyApi.CouponId> = core.schemas.string();

export declare namespace CouponId {
  type Raw = string;
}
