/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../../../core";

export const CreateSubscriptionRequest: core.serialization.Schema<
    serializers.CreateSubscriptionRequest.Raw,
    CorrilyApi.CreateSubscriptionRequest
> = core.serialization.object({
    amount: core.serialization.number(),
    country: core.serialization.lazy(async () => (await import("../../../..")).Country).optional(),
    created: core.serialization.number(),
    currency: core.serialization.lazy(async () => (await import("../../../..")).Currency),
    origin: core.serialization.lazy(async () => (await import("../../../..")).Integration),
    originId: core.serialization.property("origin_id", core.serialization.string()),
    product: core.serialization.string(),
    status: core.serialization.lazy(async () => (await import("../../../..")).SubscriptionStatus),
    userId: core.serialization.property(
        "user_id",
        core.serialization.lazy(async () => (await import("../../../..")).UserId)
    ),
    cancelAt: core.serialization.property("cancel_at", core.serialization.number().optional()),
    canceledAt: core.serialization.property("canceled_at", core.serialization.number().optional()),
    trialEnd: core.serialization.property("trial_end", core.serialization.number().optional()),
    trialStart: core.serialization.property("trial_start", core.serialization.number().optional()),
});

export declare namespace CreateSubscriptionRequest {
    interface Raw {
        amount: number;
        country?: serializers.Country.Raw | null;
        created: number;
        currency: serializers.Currency.Raw;
        origin: serializers.Integration.Raw;
        origin_id: string;
        product: string;
        status: serializers.SubscriptionStatus.Raw;
        user_id: serializers.UserId.Raw;
        cancel_at?: number | null;
        canceled_at?: number | null;
        trial_end?: number | null;
        trial_start?: number | null;
    }
}
