/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ChargebeeIntegration {
    /** The matching [Chargebee plan ID](https://apidocs.chargebee.com/docs/api/plans?prod_cat_ver=1#plan_id). */
    chargebeePlanId: string;
}
