/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RecurlyIntegration {
    /** The matching [Recurly plan ID](https://developers.recurly.com/api/v2021-02-25/index.html#operation/create_plan). */
    recurlyPlanId: string;
}
