/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The frequency at which a subscription is billed.
 */
export type StripeInterval = "day" | "week" | "month" | "year";

export const StripeInterval = {
    Day: "day",
    Week: "week",
    Month: "month",
    Year: "year",
} as const;
