/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CorrilyApi } from "@fern-api/corrily";

export interface CreateChargeRequest {
  amount: number;
  amountRefunded?: number;
  created: number;
  currency: CorrilyApi.Currency;
  country?: string;
  origin: CorrilyApi.Integration;
  originId: CorrilyApi.OriginId;
  product: string;
  status?: CorrilyApi.ChargeStatus;
  userId: CorrilyApi.UserId;
  metadata?: unknown;
}
