/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../../core";

export const IdentifyCallResponse: core.serialization.ObjectSchema<
    serializers.IdentifyCallResponse.Raw,
    CorrilyApi.IdentifyCallResponse
> = core.serialization.object({
    status: core.serialization.string().optional(),
});

export declare namespace IdentifyCallResponse {
    interface Raw {
        status?: string | null;
    }
}
