/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CorrilyApi } from "@fern-api/corrily";

export interface UpdateChargeRequest {
    amount?: number;
    created?: number;
    currency?: CorrilyApi.Currency;
    status?: CorrilyApi.ChargeStatus;
    userId: CorrilyApi.UserId;
    metadata?: unknown;
}
