/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { CorrilyApi } from "@fern-api/corrily";
import urlJoin from "url-join";
import * as serializers from "../../../../serialization";
import * as errors from "../../../../errors";

export declare namespace Client {
    interface Options {
        environment?: environments.CorrilyApiEnvironment | string;
        token?: core.Supplier<core.BearerToken>;
    }
}

export class Client {
    constructor(private readonly options: Client.Options) {}

    /**
     * Notify Corrily that one of your customers has initiated a one-time transaction.
     */
    public async create(request: CorrilyApi.CreateChargeRequest): Promise<void> {
        const _response = await core.fetcher({
            url: urlJoin(this.options.environment ?? environments.CorrilyApiEnvironment.Production, "/charges"),
            method: "POST",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
            body: await serializers.CreateChargeRequest.json(request),
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            throw new errors.CorrilyApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.CorrilyApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.CorrilyApiTimeoutError();
            case "unknown":
                throw new errors.CorrilyApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    public async get(
        origin: CorrilyApi.Integration,
        originId: string,
        userId: string
    ): Promise<CorrilyApi.GetChargeResponse | undefined> {
        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.CorrilyApiEnvironment.Production,
                `/charges/${userId}/${origin}/${originId}`
            ),
            method: "GET",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
        });
        if (_response.ok) {
            return await serializers.GetChargeResponse.parse(_response.body as serializers.GetChargeResponse.Raw);
        }

        if (_response.error.reason === "status-code") {
            throw new errors.CorrilyApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.CorrilyApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.CorrilyApiTimeoutError();
            case "unknown":
                throw new errors.CorrilyApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    public async update(
        origin: CorrilyApi.Integration,
        originId: string,
        userId: string,
        request: CorrilyApi.UpdateChargeRequest
    ): Promise<CorrilyApi.UpdateChargeResponse | undefined> {
        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.CorrilyApiEnvironment.Production,
                `/charges/${userId}/${origin}/${originId}`
            ),
            method: "POST",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
            body: await serializers.UpdateChargeRequest.json(request),
        });
        if (_response.ok) {
            return await serializers.UpdateChargeResponse.parse(_response.body as serializers.UpdateChargeResponse.Raw);
        }

        if (_response.error.reason === "status-code") {
            throw new errors.CorrilyApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.CorrilyApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.CorrilyApiTimeoutError();
            case "unknown":
                throw new errors.CorrilyApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    public async delete(origin: CorrilyApi.Integration, originId: string, userId: string): Promise<void> {
        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.CorrilyApiEnvironment.Production,
                `/charges/${userId}/${origin}/${originId}`
            ),
            method: "DELETE",
            headers: {
                Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
            },
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            throw new errors.CorrilyApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.CorrilyApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.CorrilyApiTimeoutError();
            case "unknown":
                throw new errors.CorrilyApiError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
