/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../../../core";

export const IdentifyCallRequest: core.serialization.Schema<
    serializers.IdentifyCallRequest.Raw,
    CorrilyApi.IdentifyCallRequest
> = core.serialization.object({
    userId: core.serialization.property(
        "user_id",
        core.serialization.lazy(async () => (await import("../../../..")).UserId)
    ),
    ip: core.serialization.string().optional(),
    features: core.serialization.unknown().optional(),
    appleOriginalTransactionId: core.serialization.property(
        "apple_original_transaction_id",
        core.serialization.string().optional()
    ),
    googlePurchaseToken: core.serialization.property("google_purchase_token", core.serialization.string().optional()),
});

export declare namespace IdentifyCallRequest {
    interface Raw {
        user_id: serializers.UserId.Raw;
        ip?: string | null;
        features?: unknown | null;
        apple_original_transaction_id?: string | null;
        google_purchase_token?: string | null;
    }
}
