/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../../../core";

export const CalculatePriceRequest: core.serialization.Schema<
    serializers.CalculatePriceRequest.Raw,
    CorrilyApi.CalculatePriceRequest
> = core.serialization.object({
    userId: core.serialization.property(
        "user_id",
        core.serialization.lazy(async () => (await import("../../../..")).UserId).optional()
    ),
    products: core.serialization.list(core.serialization.lazy(async () => (await import("../../../..")).ProductId)),
    ip: core.serialization.string().optional(),
    getIpFromRequest: core.serialization.property("get_ip_from_request", core.serialization.boolean().optional()),
    country: core.serialization.lazy(async () => (await import("../../../..")).Country).optional(),
    features: core.serialization.lazy(async () => (await import("../../../..")).PriceFeatures).optional(),
    integrations: core.serialization
        .list(core.serialization.lazy(async () => (await import("../../../..")).Integration))
        .optional(),
    currency: core.serialization.lazy(async () => (await import("../../../..")).Currency).optional(),
    override: core.serialization.boolean().optional(),
    overrideCurrency: core.serialization.property("override_currency", core.serialization.boolean().optional()),
    runExperiment: core.serialization.property("run_experiment", core.serialization.boolean().optional()),
    coupons: core.serialization.lazy(async () => (await import("../../../..")).Coupons).optional(),
});

export declare namespace CalculatePriceRequest {
    interface Raw {
        user_id?: serializers.UserId.Raw | null;
        products: serializers.ProductId.Raw[];
        ip?: string | null;
        get_ip_from_request?: boolean | null;
        country?: serializers.Country.Raw | null;
        features?: serializers.PriceFeatures.Raw | null;
        integrations?: serializers.Integration.Raw[] | null;
        currency?: serializers.Currency.Raw | null;
        override?: boolean | null;
        override_currency?: boolean | null;
        run_experiment?: boolean | null;
        coupons?: serializers.Coupons.Raw | null;
    }
}
