/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../../core";

export const CreateSubscriptionResponse: core.serialization.Schema<
    serializers.CreateSubscriptionResponse.Raw,
    CorrilyApi.CreateSubscriptionResponse
> = core.serialization.unknown();

export declare namespace CreateSubscriptionResponse {
    type Raw = unknown;
}
