/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../../core";

export const DeleteSubscriptionResponse: core.serialization.Schema<
    serializers.DeleteSubscriptionResponse.Raw,
    CorrilyApi.DeleteSubscriptionResponse
> = core.serialization.unknown();

export declare namespace DeleteSubscriptionResponse {
    type Raw = unknown;
}
