/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../../core";

export const SubscriptionStatus: core.serialization.Schema<
    serializers.SubscriptionStatus.Raw,
    CorrilyApi.SubscriptionStatus
> = core.serialization.enum_(["pending", "trialing", "active", "canceled"]);

export declare namespace SubscriptionStatus {
    type Raw = "pending" | "trialing" | "active" | "canceled";
}
