/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../core";

export const Coupons: core.schemas.Schema<serializers.Coupons.Raw, CorrilyApi.Coupons> = core.schemas.record(
  core.schemas.lazy(async () => (await import("../..")).ProductId),
  core.schemas.string()
);

export declare namespace Coupons {
  type Raw = Record<serializers.ProductId.Raw, string>;
}
