/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../core";

export const PriceFeatures: core.schemas.Schema<serializers.PriceFeatures.Raw, CorrilyApi.PriceFeatures> =
  core.schemas.record(core.schemas.string(), core.schemas.string());

export declare namespace PriceFeatures {
  type Raw = Record<string, string>;
}
