/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../core";

export const TreatmentGroup: core.schemas.Schema<serializers.TreatmentGroup.Raw, CorrilyApi.TreatmentGroup> =
  core.schemas.enum_(["baseline"]);

export declare namespace TreatmentGroup {
  type Raw = "baseline";
}
