/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ChargeStatus = "pending" | "succeeded" | "failed";

export const ChargeStatus = {
  Pending: "pending",
  Succeeded: "succeeded",
  Failed: "failed",
} as const;
