/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../core";

export const GetChargeResponse: core.schemas.Schema<serializers.GetChargeResponse.Raw, CorrilyApi.GetChargeResponse> =
  core.schemas.unknown();

export declare namespace GetChargeResponse {
  type Raw = unknown;
}
