/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CorrilyApi } from "@fern-api/corrily";

export interface StripeWithIntervalIntegration {
  /** The matching [Stripe product ID](https://stripe.com/docs/api/products/object#product_object-id) */
  stripeProductId: string;
  /**
   * The frequency at which a subscription is billed.
   * One of `day`, `week`, `month` or `year`.
   * Sometimes Stripe products actually encompass more than what Corrily would consider a product. For example, the Stripe product for a company's "Pro Plan" might have two [Price objects](https://stripe.com/docs/api/prices/object) one for the monthly version of the plan, the other for its annual version. Meanwhile, Corrily would consider these to be two distinct products `pro_monthly` and `pro_annual`.
   * To capture such differences you can pass a `stripe_with_interval` integration object which can help separate such cases.
   *
   */
  interval: CorrilyApi.StripeInterval;
  /** The number of intervals (specified in the interval attribute) between subscription billings. For example, interval=month and interval_count=3 bills every 3 months. */
  intervalCount: number;
}
