/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface StripeIntegration {
  /** The matching [Stripe product ID](https://stripe.com/docs/api/products/object#product_object-id) */
  stripeProductId: string;
}
