/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CorrilyApi } from "@fern-api/corrily";

export interface UpdateSubscriptionRequest {
  amount?: number;
  cancelAt?: number;
  canceledAt?: number;
  created?: number;
  currency?: string;
  status?: CorrilyApi.SubscriptionStatus;
  trialStart?: number;
  trialEnd?: number;
}
