/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Integration = "stripe" | "paypal" | "chargebee";

export const Integration = {
    Stripe: "stripe",
    Paypal: "paypal",
    Chargebee: "chargebee",
} as const;
