/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Interval = "day" | "week" | "monthly" | "year" | "one-time";

export const Interval = {
    Day: "day",
    Week: "week",
    Monthly: "monthly",
    Year: "year",
    OneTime: "one-time",
} as const;
