/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const CorrilyApiEnvironment = {
  Production: "https://default.corrily.com/mainapi/v1",
} as const;

export type CorrilyApiEnvironment = typeof CorrilyApiEnvironment.Production;
