/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../core";

export const Request: core.schemas.Schema<
  serializers.subscription.create.Request.Raw,
  CorrilyApi.CreateSubscriptionRequest
> = core.schemas.object({
  amount: core.schemas.number(),
  country: core.schemas.lazy(async () => (await import("../..")).Country).optional(),
  created: core.schemas.number(),
  currency: core.schemas.lazy(async () => (await import("../..")).Currency),
  origin: core.schemas.lazy(async () => (await import("../..")).Integration),
  originId: core.schemas.property("origin_id", core.schemas.string()),
  product: core.schemas.string(),
  status: core.schemas.lazy(async () => (await import("../..")).SubscriptionStatus),
  userId: core.schemas.property(
    "user_id",
    core.schemas.lazy(async () => (await import("../..")).UserId)
  ),
  cancelAt: core.schemas.property("cancel_at", core.schemas.number().optional()),
  canceledAt: core.schemas.property("canceled_at", core.schemas.number().optional()),
  trialEnd: core.schemas.property("trial_end", core.schemas.number().optional()),
  trialStart: core.schemas.property("trial_start", core.schemas.number().optional()),
});

export declare namespace Request {
  interface Raw {
    amount: number;
    country?: serializers.Country.Raw | null;
    created: number;
    currency: serializers.Currency.Raw;
    origin: serializers.Integration.Raw;
    origin_id: string;
    product: string;
    status: serializers.SubscriptionStatus.Raw;
    user_id: serializers.UserId.Raw;
    cancel_at?: number | null;
    canceled_at?: number | null;
    trial_end?: number | null;
    trial_start?: number | null;
  }
}

export const Response: core.schemas.Schema<
  serializers.subscription.create.Response.Raw,
  CorrilyApi.CreateSubscriptionResponse | undefined
> = core.schemas.lazy(async () => (await import("../..")).CreateSubscriptionResponse);

export declare namespace Response {
  type Raw = serializers.CreateSubscriptionResponse.Raw | undefined;
}
