/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../core";

export const Response: core.schemas.Schema<
  serializers.subscription.get.Response.Raw,
  CorrilyApi.GetSubscriptionResponse | undefined
> = core.schemas.lazy(async () => (await import("../..")).GetSubscriptionResponse);

export declare namespace Response {
  type Raw = serializers.GetSubscriptionResponse.Raw | undefined;
}
