/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ExperimentType = "price" | "packaging" | "null";

export const ExperimentType = {
  Price: "price",
  Packaging: "packaging",
  Null: "null",
} as const;
