/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * You can provide whatever keys and values you want.
 * The keys and values have no intrinsic meaning to Corrily.
 * To Corrily these are simply labels for training its AI models. For example, suppose that you provide a platform
 *
 */
export type PriceFeatures = Record<unknown, unknown>;
