/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PriceDisplay {
  /**
   * The price data, formatted in a way that your user will quickly understand.
   * This is usually a combination of `currency`, `currency_symbol`, and `products.{id}.price`.
   * `products.{id}.price` will use commas or periods as separators if that is the local custom.
   * Example: `JP¥2,200`
   *
   */
  price?: string;
  /** The default price for the product. You can set this default price in your Corrily Dashboard. */
  referenceIntervalPrice?: string;
  /**
   * If products.{id}.price is an experimental price, this field contains the baseline price striked out, followed by the experimental price.
   * You may want to present this to your user to help them see that they would be paying less than normal customers.
   * Example: $̶3̶4̶ $19
   *
   */
  priceWithBaselineStrike?: string;
  /**
   * If `products.{id}.price` is an experimental price, this field contains the percentage discount of the experimental price compared to the baseline price.
   * For example, if the baseline price is 34 and the experimental price is 19, the discount is about 44%: 1 - (19 ÷ 34)) × 100
   *
   */
  discountToBaseline?: number;
}
