/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../../core";

export const CountryPrice: core.serialization.ObjectSchema<serializers.CountryPrice.Raw, CorrilyApi.CountryPrice> =
    core.serialization.object({
        country: core.serialization.lazy(async () => (await import("../../..")).Country),
        localCurrency: core.serialization.property("local_currency", core.serialization.number()),
        currency: core.serialization.lazy(async () => (await import("../../..")).Currency),
    });

export declare namespace CountryPrice {
    interface Raw {
        country: serializers.Country.Raw;
        local_currency: number;
        currency: serializers.Currency.Raw;
    }
}
