/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../../core";

export const Country: core.serialization.Schema<serializers.Country.Raw, CorrilyApi.Country> = core.serialization.enum_(
    ["US", "CA", "SG", "IT"]
);

export declare namespace Country {
    type Raw = "US" | "CA" | "SG" | "IT";
}
