/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../../core";

export const Currency: core.serialization.Schema<serializers.Currency.Raw, CorrilyApi.Currency> =
    core.serialization.enum_(["USD", "SGD", "EUR"]);

export declare namespace Currency {
    type Raw = "USD" | "SGD" | "EUR";
}
