/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../../core";

export const Integration: core.serialization.Schema<serializers.Integration.Raw, CorrilyApi.Integration> =
    core.serialization.enum_(["stripe", "paypal", "chargebee"]);

export declare namespace Integration {
    type Raw = "stripe" | "paypal" | "chargebee";
}
