/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../../core";

export const Interval: core.serialization.Schema<serializers.Interval.Raw, CorrilyApi.Interval> =
    core.serialization.enum_(["day", "week", "monthly", "year", "one-time"]);

export declare namespace Interval {
    type Raw = "day" | "week" | "monthly" | "year" | "one-time";
}
