/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CorrilyApi } from "@fern-api/corrily";
import * as core from "../../../../core";

export const OriginId: core.serialization.Schema<serializers.OriginId.Raw, CorrilyApi.OriginId> =
    core.serialization.string();

export declare namespace OriginId {
    type Raw = string;
}
