/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CorrilyApi } from "@fern-api/corrily";

export interface Gateway {
    /**
     * The currency that `products.{id}.integrations.{gateway}.amount` is priced in.
     * If this currency is not the same as the top-level `currency` value in this response (the “local currency”), it means that the payment gateway does not accept the local currency.
     *
     */
    currency?: CorrilyApi.Currency;
    /**
     * The amount that you should pass to the payment gateway when creating the subscription or charge.
     * Many payment gateways use [smallest-unit currency format](https://docs.corrily.com/payment-gateways/integration-guide#map-smallest-unit-currency-format-to-decimal-format) in which case this value will be an integer.
     *
     */
    amount?: number;
    /**
     * As mentioned in `products.{id}.integrations.{gateway}.currency`, sometimes a payment gateway doesn't support your user's local currency.
     * If that's the case, then `products.{id}.integrations.{gateway}.formatted` provides the equivalent price in a currency that the payment gateway does support.
     * This field is similar to `products.{id}.display.price` in that it will be formatted in a way that your user will quickly understand.
     *
     */
    formatted?: string;
}
