/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CorrilyApi } from "@fern-api/corrily";

/**
 * Price experimentation metadata.
 * If you are not doing price experimentation, you can ignore this object.
 *
 */
export interface Variants {
    /** Whether or not this response contains experimental prices. */
    experimentedOn?: boolean;
    /** The ID of this experiment. An id of `0` means no experiment was run. */
    experimentId?: number;
    experimentType?: CorrilyApi.ExperimentType;
    /** In the case of a `packaging` experiment, the product API IDs to pick from the `product` object of the response to show to users. */
    productsToSelect?: string[];
    /** The experiment arm identifier, equal to `baseline` if experiment is run but baseline arm was selected. */
    treatmentGroup?: CorrilyApi.TreatmentGroup;
}
